name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  widgetbook_annotation: ^3.2.0
  widgetbook: ^3.10.0
  cupertino_icons: ^1.0.6
  gengar_dex:
    path: ../

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.9.0


flutter:
  uses-material-design: true
